### ISSUE TITLE
Display user location on Landing page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#14]
**User Story Description**
As an end user 
I want to see my location (country, state, city) displayed on the screen 
So I can verify my location

**Steps to Follow (optional)**
- [x] Add template city, state & country name to test layout
- [x] Map out how to use [Geolocation API](https://tinyurl.com/y3lfs2et) to find user location
- [x] Identify how to translate geolocation into city, state, & country name
- [x] Write code to add location info to the page from the API
- [x] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by OmarAlareeki** [comment]
I have completed this issue, just have a bug trying to fix. The problem with the bug is the location of the country and state do not change when the user changes the location in the input. The geolocation.js the file which responsible to fetch the user location, ask the user to allow location then the info of the user displayed for the current location. However, when the user changes the location later, the country and state do not change. This is a small bug and will be fixed soon. Maybe closed for this issue.

**Comment by thiagorasouza** [comment]
> I have completed this issue, just have a bug trying to fix. The problem with the bug is the location of the country and state do not change when the user changes the location in the input. The geolocation.js the file which responsible to fetch the user location, ask the user to allow location then the info of the user displayed for the current location. However, when the user changes the location later, the country and state do not change. This is a small bug and will be fixed soon. Maybe closed for this issue.

Hey @OmarAlareeki, I think that may be solved by updating weather.js, function update(), line 99 at your branch, or creating a new function inside geolocation.js
